BEGIN TRANSACTION;

ALTER TABLE Evaluations ADD timestamp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Evaluations ADD checkouttime INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Evaluations ADD evaltime INTEGER NOT NULL DEFAULT 0;

ALTER TABLE Checkouts ADD timestamp INTEGER NOT NULL DEFAULT 0;

COMMIT;
